baseURL = 'https://mwbh.github.io'
languageCode = 'ko-kr'
title = 'MWBH'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
